import type { PlanId, PlanSpec, Product } from './types.ts'

const MB_15 = [
  { year: 6, pct: 20 },
  { year: 9, pct: 20 },
  { year: 12, pct: 20 },
  { year: 15, pct: 40 },
]
const MB_20 = [
  { year: 8, pct: 20 },
  { year: 12, pct: 20 },
  { year: 16, pct: 20 },
  { year: 20, pct: 40 },
]
const MB_10 = [
  { year: 4, pct: 20 },
  { year: 7, pct: 20 },
  { year: 10, pct: 60 },
]

export const PLANS: PlanSpec[] = [
  // ───────────────────────────── PLI ─────────────────────────────
  {
    id: 'pli-suraksha',
    product: 'PLI',
    kind: 'WLA',
    code: 'WLA',
    name: { en: 'Suraksha', hi: 'सुरक्षा' },
    tagline: { en: 'Whole Life Assurance', hi: 'आजीवन बीमा' },
    icon: 'Shield',
    minAge: 19,
    maxAge: 55,
    minSA: 20_000,
    maxSA: 5_000_000,
    saStep: 10_000,
    bonusRate: 76,
    term: { type: 'ceasingAge', options: [55, 58, 60] },
    loanAfterYears: 4,
    surrenderAfterYears: 3,
    bonusVestingYears: 5,
    features: [
      { en: 'SA + bonus at 80 years or death', hi: '80 वर्ष या मृत्यु पर SA + बोनस' },
      { en: 'Premium stops at 55 / 58 / 60', hi: '55 / 58 / 60 पर प्रीमियम बंद' },
      { en: 'Loan after 4 years', hi: '4 वर्ष बाद ऋण' },
    ],
  },
  {
    id: 'pli-santosh',
    product: 'PLI',
    kind: 'EA',
    code: 'EA',
    name: { en: 'Santosh', hi: 'संतोष' },
    tagline: { en: 'Endowment Assurance', hi: 'बंदोबस्ती बीमा' },
    icon: 'Smile',
    minAge: 19,
    maxAge: 55,
    minSA: 20_000,
    maxSA: 5_000_000,
    saStep: 10_000,
    bonusRate: 52,
    term: { type: 'maturityAge', options: [35, 40, 45, 50, 55, 58, 60] },
    loanAfterYears: 3,
    surrenderAfterYears: 3,
    bonusVestingYears: 5,
    features: [
      { en: 'SA + bonus at maturity age', hi: 'परिपक्वता आयु पर SA + बोनस' },
      { en: 'Maturity at 35 – 60 years', hi: '35 – 60 वर्ष पर परिपक्वता' },
      { en: 'Loan after 3 years', hi: '3 वर्ष बाद ऋण' },
    ],
  },
  {
    id: 'pli-suvidha',
    product: 'PLI',
    kind: 'CWLA',
    code: 'CWLA',
    name: { en: 'Suvidha', hi: 'सुविधा' },
    tagline: { en: 'Convertible Whole Life', hi: 'परिवर्तनीय आजीवन बीमा' },
    icon: 'RefreshCw',
    minAge: 19,
    maxAge: 55,
    minSA: 20_000,
    maxSA: 5_000_000,
    saStep: 10_000,
    bonusRate: 76,
    bonusRateAfterConversion: 52,
    term: { type: 'ceasingAge', options: [55, 58, 60] },
    conversionWindow: { earliestYear: 5, latestYear: 6 },
    loanAfterYears: 4,
    surrenderAfterYears: 3,
    bonusVestingYears: 5,
    features: [
      { en: 'Convert to Endowment after 5 years', hi: '5 वर्ष बाद बंदोबस्ती में बदलें' },
      { en: '₹76 bonus (WLA) / ₹52 after conversion', hi: '₹76 बोनस (WLA) / रूपांतरण के बाद ₹52' },
      { en: 'Loan after 4 years', hi: '4 वर्ष बाद ऋण' },
    ],
  },
  {
    id: 'pli-sumangal',
    product: 'PLI',
    kind: 'AEA',
    code: 'AEA',
    name: { en: 'Sumangal', hi: 'सुमंगल' },
    tagline: { en: 'Anticipated Endowment (Money Back)', hi: 'प्रत्याशित बंदोबस्ती (मनी बैक)' },
    icon: 'Coins',
    minAge: 19,
    maxAge: 45,
    minSA: 20_000,
    maxSA: 5_000_000,
    saStep: 10_000,
    bonusRate: 48,
    term: { type: 'fixedTerm', options: [15, 20] },
    moneyBack: { 15: MB_15, 20: MB_20 },
    maxAgeByTerm: { 15: 45, 20: 40 },
    loanAfterYears: 3,
    surrenderAfterYears: 3,
    bonusVestingYears: 5,
    features: [
      { en: '20% money-back every few years', hi: 'हर कुछ वर्षों में 20% मनी-बैक' },
      { en: '40% + full bonus at the end', hi: 'अंत में 40% + पूरा बोनस' },
      { en: 'Full SA on death, even after payouts', hi: 'भुगतान के बाद भी मृत्यु पर पूरा SA' },
    ],
  },
  {
    id: 'pli-yugal-suraksha',
    product: 'PLI',
    kind: 'JOINT',
    code: 'JLA',
    name: { en: 'Yugal Suraksha', hi: 'युगल सुरक्षा' },
    tagline: { en: 'Joint Life Assurance', hi: 'संयुक्त जीवन बीमा' },
    icon: 'HeartHandshake',
    minAge: 21,
    maxAge: 45,
    minSA: 20_000,
    maxSA: 5_000_000,
    saStep: 10_000,
    bonusRate: 52,
    term: { type: 'termRange', min: 5, max: 20, default: 20 },
    joint: true,
    loanAfterYears: 3,
    surrenderAfterYears: 3,
    bonusVestingYears: 5,
    features: [
      { en: 'Covers both spouses in one policy', hi: 'एक पॉलिसी में दोनों पति-पत्नी' },
      { en: 'SA + bonus on first death or maturity', hi: 'पहली मृत्यु या परिपक्वता पर SA + बोनस' },
      { en: 'Term 5 – 20 years', hi: 'अवधि 5 – 20 वर्ष' },
    ],
  },
  {
    id: 'pli-bal-jeevan',
    product: 'PLI',
    kind: 'CHILD',
    code: 'CP',
    name: { en: 'Bal Jeevan Bima', hi: 'बाल जीवन बीमा' },
    tagline: { en: 'Children Policy', hi: 'बच्चों की पॉलिसी' },
    icon: 'Baby',
    minAge: 5,
    maxAge: 20,
    minSA: 20_000,
    maxSA: 300_000,
    saStep: 10_000,
    bonusRate: 52,
    term: { type: 'termRange', min: 5, max: 20, default: 15 },
    child: { minChildAge: 5, maxChildAge: 20, maxParentAge: 45 },
    loanAfterYears: 3,
    surrenderAfterYears: 3,
    bonusVestingYears: 5,
    features: [
      { en: 'Max 2 children, SA up to ₹3 lakh', hi: 'अधिकतम 2 बच्चे, SA ₹3 लाख तक' },
      { en: 'No premium after parent’s death', hi: 'माता-पिता की मृत्यु के बाद प्रीमियम नहीं' },
      { en: 'Parent age ≤ 45', hi: 'माता-पिता की आयु ≤ 45' },
    ],
  },
  // ───────────────────────────── RPLI ─────────────────────────────
  {
    id: 'rpli-gram-suraksha',
    product: 'RPLI',
    kind: 'WLA',
    code: 'WLA',
    name: { en: 'Gram Suraksha', hi: 'ग्राम सुरक्षा' },
    tagline: { en: 'Whole Life Assurance', hi: 'आजीवन बीमा' },
    icon: 'Shield',
    minAge: 19,
    maxAge: 55,
    minSA: 10_000,
    maxSA: 1_000_000,
    saStep: 10_000,
    bonusRate: 60,
    term: { type: 'ceasingAge', options: [55, 58, 60] },
    loanAfterYears: 4,
    surrenderAfterYears: 3,
    bonusVestingYears: 5,
    features: [
      { en: 'SA + bonus at 80 years or death', hi: '80 वर्ष या मृत्यु पर SA + बोनस' },
      { en: 'Premium stops at 55 / 58 / 60', hi: '55 / 58 / 60 पर प्रीमियम बंद' },
      { en: 'Loan after 4 years', hi: '4 वर्ष बाद ऋण' },
    ],
  },
  {
    id: 'rpli-gram-santosh',
    product: 'RPLI',
    kind: 'EA',
    code: 'EA',
    name: { en: 'Gram Santosh', hi: 'ग्राम संतोष' },
    tagline: { en: 'Endowment Assurance', hi: 'बंदोबस्ती बीमा' },
    icon: 'Smile',
    minAge: 19,
    maxAge: 55,
    minSA: 10_000,
    maxSA: 1_000_000,
    saStep: 10_000,
    bonusRate: 48,
    term: { type: 'maturityAge', options: [35, 40, 45, 50, 55, 58, 60] },
    loanAfterYears: 3,
    surrenderAfterYears: 3,
    bonusVestingYears: 5,
    features: [
      { en: 'SA + bonus at maturity age', hi: 'परिपक्वता आयु पर SA + बोनस' },
      { en: 'Maturity at 35 – 60 years', hi: '35 – 60 वर्ष पर परिपक्वता' },
      { en: 'Loan after 3 years', hi: '3 वर्ष बाद ऋण' },
    ],
  },
  {
    id: 'rpli-gram-suvidha',
    product: 'RPLI',
    kind: 'CWLA',
    code: 'CWLA',
    name: { en: 'Gram Suvidha', hi: 'ग्राम सुविधा' },
    tagline: { en: 'Convertible Whole Life', hi: 'परिवर्तनीय आजीवन बीमा' },
    icon: 'RefreshCw',
    minAge: 19,
    maxAge: 55,
    minSA: 10_000,
    maxSA: 1_000_000,
    saStep: 10_000,
    bonusRate: 60,
    bonusRateAfterConversion: 48,
    term: { type: 'ceasingAge', options: [55, 58, 60] },
    conversionWindow: { earliestYear: 5, latestYear: 6 },
    loanAfterYears: 4,
    surrenderAfterYears: 3,
    bonusVestingYears: 5,
    features: [
      { en: 'Convert to Endowment after 5 years', hi: '5 वर्ष बाद बंदोबस्ती में बदलें' },
      { en: '₹60 bonus (WLA) / ₹48 after conversion', hi: '₹60 बोनस (WLA) / रूपांतरण के बाद ₹48' },
      { en: 'Loan after 4 years', hi: '4 वर्ष बाद ऋण' },
    ],
  },
  {
    id: 'rpli-gram-sumangal',
    product: 'RPLI',
    kind: 'AEA',
    code: 'AEA',
    name: { en: 'Gram Sumangal', hi: 'ग्राम सुमंगल' },
    tagline: { en: 'Anticipated Endowment (Money Back)', hi: 'प्रत्याशित बंदोबस्ती (मनी बैक)' },
    icon: 'Coins',
    minAge: 19,
    maxAge: 45,
    minSA: 10_000,
    maxSA: 1_000_000,
    saStep: 10_000,
    bonusRate: 45,
    term: { type: 'fixedTerm', options: [15, 20] },
    moneyBack: { 15: MB_15, 20: MB_20 },
    maxAgeByTerm: { 15: 45, 20: 40 },
    loanAfterYears: 3,
    surrenderAfterYears: 3,
    bonusVestingYears: 5,
    features: [
      { en: '20% money-back every few years', hi: 'हर कुछ वर्षों में 20% मनी-बैक' },
      { en: '40% + full bonus at the end', hi: 'अंत में 40% + पूरा बोनस' },
      { en: 'Full SA on death, even after payouts', hi: 'भुगतान के बाद भी मृत्यु पर पूरा SA' },
    ],
  },
  {
    id: 'rpli-gram-priya',
    product: 'RPLI',
    kind: 'AEA',
    code: 'AEA-10',
    name: { en: 'Gram Priya', hi: 'ग्राम प्रिया' },
    tagline: { en: '10-Year Money Back', hi: '10-वर्षीय मनी बैक' },
    icon: 'CalendarClock',
    minAge: 20,
    maxAge: 45,
    minSA: 10_000,
    maxSA: 1_000_000,
    saStep: 10_000,
    bonusRate: 45,
    term: { type: 'fixedTerm', options: [10] },
    moneyBack: { 10: MB_10 },
    maxAgeByTerm: { 10: 45 },
    loanAfterYears: 3,
    surrenderAfterYears: 3,
    bonusVestingYears: 5,
    features: [
      { en: '20% at 4th & 7th year', hi: '4वें और 7वें वर्ष में 20%' },
      { en: '60% + bonus at 10th year', hi: '10वें वर्ष में 60% + बोनस' },
      { en: 'Short 10-year commitment', hi: 'छोटी 10-वर्षीय अवधि' },
    ],
  },
  {
    id: 'rpli-bal-jeevan',
    product: 'RPLI',
    kind: 'CHILD',
    code: 'CP',
    name: { en: 'Bal Jeevan Bima', hi: 'बाल जीवन बीमा' },
    tagline: { en: 'RPLI Children Policy', hi: 'RPLI बच्चों की पॉलिसी' },
    icon: 'Baby',
    minAge: 5,
    maxAge: 20,
    minSA: 10_000,
    maxSA: 100_000,
    saStep: 10_000,
    bonusRate: 48,
    term: { type: 'termRange', min: 5, max: 20, default: 15 },
    child: { minChildAge: 5, maxChildAge: 20, maxParentAge: 45 },
    loanAfterYears: 3,
    surrenderAfterYears: 3,
    bonusVestingYears: 5,
    features: [
      { en: 'Max 2 children, SA up to ₹1 lakh', hi: 'अधिकतम 2 बच्चे, SA ₹1 लाख तक' },
      { en: 'No premium after parent’s death', hi: 'माता-पिता की मृत्यु के बाद प्रीमियम नहीं' },
      { en: 'Parent age ≤ 45', hi: 'माता-पिता की आयु ≤ 45' },
    ],
  },
]

export const PLAN_BY_ID: Record<PlanId, PlanSpec> = Object.fromEntries(
  PLANS.map((p) => [p.id, p]),
) as Record<PlanId, PlanSpec>

export function plansFor(product: Product): PlanSpec[] {
  return PLANS.filter((p) => p.product === product)
}
